#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
sudo apt-get update
sudo apt-get install -y haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Configure HAproxy to send traffic to web-01 and web-02
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy
defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000ms
    timeout client  50000ms
    timeout server  50000ms
listen hbnb 0.0.0.0:80
    mode http
    balance roundrobin
    option httpclose
    option forwardfor
    server 127.0.0.1 237.84.2.178 check
    server 127.0.0.1 38.0.101.76 check
" | sudo dd of=/etc/haproxy/haproxy.cfg

