#!/usr/bin/env bash
#configures nginx on new ubuntu machine
sudo apt update && \
sudo apt install nginx -y

if [$? -eq 0]; then
	echo -e "http {
		root /var/www/holberton;
		index index.html;
		server {
		    listen 80;
		    location / {
	    }
    }
}
events {
}" > etc/nginx/nginx.conf

  mkdir -p /var/www/holberton
  echo "Holberton School" > /var/www/holberton/index.html
  service nginx start
  if [$? -ne 0]; then
	  echo "Problem starting ngnix"
	  exit 1

  fi
else
	echo "Could not install"
	exit 1
fi

