#!/usr/bin/env bash
#configures nginx on new ubuntu machine
apt-get update
apt-get install nginx -y
echo "Holberton School for the win!" > /var/www/html/index.html
echo "server {
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=-VGIt10m9VQ;
	}
	}" >> /etc/nginx/sites-available/default
sudo service nginx restart
